import { complementsSearch } from './complementsSearch';

test('`function complementsSearch()`', () => {
  // string inputs
  var complements = complementsSearch('UGCCA', PEMV2);

  expect([...complements].map(c => c.index)).toStrictEqual([558, 742, 2186, 2833, 3400, 3880]);
  expect([...complements].map(c => c.position)).toStrictEqual([559, 743, 2187, 2834, 3401, 3881]);

  [...complements].forEach(c => expect(c.length).toBe(5));

  // stringifiable motif and sequence
  var complements = complementsSearch(
    [...'UGCCA'].map(c => new NucleobaseMock(c)),
    [...PEMV2].map(c => new NucleobaseMock(c)),
  );

  expect([...complements].map(c => c.index)).toStrictEqual([558, 742, 2186, 2833, 3400, 3880]);
  expect([...complements].map(c => c.position)).toStrictEqual([559, 743, 2187, 2834, 3401, 3881]);

  [...complements].forEach(c => expect(c.length).toBe(5));

  // stringifiable sequence
  var complements = complementsSearch(
    'UGCCA',
    [...PEMV2].map(c => new NucleobaseMock(c)),
  );

  expect([...complements].map(c => c.index)).toStrictEqual([558, 742, 2186, 2833, 3400, 3880]);
  expect([...complements].map(c => c.position)).toStrictEqual([559, 743, 2187, 2834, 3401, 3881]);

  [...complements].forEach(c => expect(c.length).toBe(5));

  // stringifiable motif
  var complements = complementsSearch(
    [...'UGCCA'].map(c => new NucleobaseMock(c)),
    PEMV2,
  );

  expect([...complements].map(c => c.index)).toStrictEqual([558, 742, 2186, 2833, 3400, 3880]);
  expect([...complements].map(c => c.position)).toStrictEqual([559, 743, 2187, 2834, 3401, 3881]);

  [...complements].forEach(c => expect(c.length).toBe(5));

  // custom options
  var complements = complementsSearch('CUGCCA', PEMV2, {
    cutoff: 0.9,
    mismatchPenalty: -2,
    gapPenalty: -2.5,
  });

  expect([...complements].map(c => c.position)).toStrictEqual([343, 924, 1550, 2761, 2834, 3032]);

  // IUPAC codes
  var complements = complementsSearch('CYRCCA', PEMV2, {
    cutoff: 0.9,
    mismatchPenalty: -2,
    gapPenalty: -2.5,
  });

  expect([...complements].map(c => c.position)).toStrictEqual([2111, 2149, 3919, 3922, 4043]);

  var motif = [...'CUGCCA'];

  // a base with empty text content
  motif[3] = new NucleobaseMock('');

  var complements = complementsSearch(motif, PEMV2);

  expect([...complements].length).toBe(0);

  var seq = [...PEMV2];

  // bases with text content containing more than one character
  seq[100] = new NucleobaseMock('AG');
  seq[200] = new NucleobaseMock('asdf');

  var complements = complementsSearch('UGCCA', seq);

  expect([...complements].map(c => c.position)).toStrictEqual([559, 743, 2187, 2834, 3401, 3881]);

  // empty motif
  expect([...complementsSearch('', PEMV2)].length).toBe(0);

  // empty sequence
  expect([...complementsSearch('UGCCA', '')].length).toBe(0);
});

class NucleobaseMock {
  #character;

  constructor(character) {
    this.#character = character;
  }

  toString() {
    return this.#character;
  }
}

const PEMV2 = 'GGGTATTTATAGAGATCGGTATGAACTGTGTTGCTAGAATTAAGCGGTGGTTCACACCTGACTTCACCCCTGGCGAGGGTGTTAAGTCCAGAGCTCAGCTGGAAAGGGAGTTGGATCCTACTTGGGCGCTTCTCGTGTGTCAAGAGCGAGCGCGCCGCGATGCTGACAGTATCACCAATGAGTGGTACGAGGGCAGCATGGAGTGTAACCTCCTTATCCCTCGGCCCAAGGCTGAGGATGTTTTAGGCCCCTCCGTCGCCCCTGAGCCCGTGGCTCTAGTGGAGGAGATTACCCGTCCCCACGCGCCGTGCGTGGATGCCCCTGCCGTGGAGTCCAGCGAGCTGGCGGAGATTGATCCCGCTGACCTTGCCAAGTTCGACTCCCTCAATCGTCGCCTGTTGGCTGAAGCCAACTCATGCAGGGAGATAGTTCTGTGGGTGCCTCCTGGCCTACCAGCAGAGCGTGACGTGTTGCCCAGGGCACGTGGGGTGATAATGATCCCCGAAGTCCCTGCCTCCTCATACACCTTGTCCGTGAAGGTGATGGAGGCTGTGCGGTTGGCACAGGAAGTCTTGGCGTCCCTTGCCAAGAGGGCCTCAGAGAAGATGGCCCCACCAGCCCCTACCGCCCAGGCCCAGCCAGAGGCTACCCTGTCGGGATGCGACTACCCGTATCAGGAAACTGGAGCAGCAGCTGCGTGGGTGACGCCTGGCTGCATTGCCATGGAGCTTAGAGCCAAATTTGGCATCTGTAGACGGACCCCCGCTAACTTAGAGATGGGGAGTCGTGTTGCCCGCGAGCTCCTGCGGGATAACTGTGTCACCTGCAGGGAGACCACGTGGTACACGAGTGCCATTGCTGTGGACCTGTGGTTGACCCCAACGGTCGTCGACCTAGCCTGTGGTCGGCGGGCGGTGGATTTTTGGTAGGGGCTGTGCTGCCTCGGCTGGGGGAAGACACTAGTGTAAGGTTTGACAACCTGCACCCCAGCATCGAGGTAATCAAGGCGGCTAGGCCCCGCCCAACCCAGAGGATGTCGTACCAAATCGACGTTGTGCGTCCTCTCGGTGATTTTGGTGTGCACAACAACTCCCTTGTCAACCTAGCCAGGGGAATCAATGAAAGGGTGTTCTACACGGACAATGCTAGGACAGAACCCCTCAAGCCTAAGGTTCCCTTTCCCTCGTCACGGGAACTGAAAACCTTCAGAGTCACCCCTTGGACCATGGATAGGGTTGTGGAAAGTTACACTGGGTCTCAGCGCATTCGTTATGCTAGCGCACGGGACAGCATTTTATCCAACCCACTGAGTTCTAAGGATGCCCGGGTCAAGACGTTTGTGAAAGCTGAAAAGATAAATTTTACAGCCAAACCTGACCCCGCCCCTCGTGTGATACAGCCTAGGGATCCACGATTCAACATTGTCCTGGCTAAGTATATCAAGCCATTGGAACCGATGTTGTACAAAGCTCTCGGGAGACTTTACAAGTACCCCGCAGTCGCTAAGGGGTTTAACGCGGTTGAGACGGGAGAAATCATCGCTGGGAAATGGCGGTGTTTTAAAGATCCCGTTGTCGTGGGATTAGACGCTTCCCGATTTGATCAGCATGTATCTGTTGAGGCGTTGCAATTTACCCACGCAGTGTACAGGGGGTTCATCAAGTCCCGGGAGTTCAACAACCTCCTGCAGATGATGTACACCAACCGTGGGCTAGGGTCTGCTAAGGACGGGTTTGTCCGTTACAAGGTTAAGGGCAGACGCATGAGCGGAGATATGGACACCTCCTTGGGAAACTGCGTTCTCATGGTGTTACTCACCAGGAATCTTTGCAAGATTCTAGGCATCCCGCACGAGCTCTTCAACAATGGTGACGATTGTATCGTCTTTTTTGATCGCTGCCATTTGGAAAAGTTCAACAATGCTGTCAAGCCCTATTTTGCAGACCTCGGGTTTAAGATGAAGGTGGAGCCACCGGTAGACGTGCTCGAGAAAGTTGAGTTCTGCCAAACACAGCCTATATATGACGGGGAGAAGTGGCGCACCGTGCGCAGCATCTCGAGCATTGGGAAAGACTGCTCATCCGTCATTGGTTGGGACCAATTAGAGGGGTGGTGGGATGCCATCGCCCAGAGTGGTCTGGCTGTGTGTGGTGGGATGCCCATATACACGTCGTTTTACCGGTGGTTGGCACGGGCTGGTAAAAGTGGGACTAAGTGCCAGTCACACCCTTTATGGAAGAACGAGGGGTTGAATTGGTACAGGATGGGGATGGACCTTTCTCATGAAGTCAATGTCACCCCTCAGGCGCGTCTGTCTTTTTTCGCGGGGTTTGGAATTTCCCCCCCCATGCAGGTTGCTATTGAGGCGTTGTATGACAGGCTACCTCCACCGTCCCCCCACTACGGCTCTCCGGTTACGGTTGTAACACAGCGAGTGTTCACCAATTATTTCACGCCGGAAGCTACCTGTGTCAGCATGAGCACCAATGGAGACAACAAATCTGACTTTGCTGTGTACGGTCCTGCGCCGACAGTGATGTCTCTCTGCGCTCAGTGTTAGGCTTGTAATAGCGATGGCGTGGCTCGACCACACCCTGGATAGACAGGGTTTAGATCAAGGGAAGCCGGGGAGTCACCAACCCCACCCTGAATCGACAGGGCAAAAAGGGAAGCCGGGCATCGCCCACGTGGAATTGACCACGTCACCTTTTCGCGTCGACTGTATTGTCAACACCCCTTCGGTCCGCCAGCCTAGGACAATGGCGGTTGGGTGATATATGACGATAATCATTAATGTCAACAACGACGAGCGCAAGCAACCAGAAGGAGCTACTGGCAGCTCTGTACGGCGAGGTGACAATAAAGGAACTCGAGGAAACAAACCTCGGAGTCATCACCCCGGTTCGCGCGAACGAAAAGGTTACACTCACCCCTCTCCTACCCCCAAAAACTCAAGGCAGGGTCAGCTCCGTCCTGAAGCGGTTCAGGAGCACCCGAAACACGGGGGGACTACTTTCCGTGGAGAAAGTAGTGGTAGTGTTCACCCCTCACGTCCCAGACGACGTGCTAGGAGAGGTGGAGATATGGCTCCACGACAGCATCCTCCCCCACCTCGGGAGCGTCGGACCAAGGTTGAGACTCAAGCTGAGCGACGGGCCCAAGCTCTTAGCGTTTTACCCACCCTACTCGATTGCATTGGGGGACTCAATCTCGGGCCAGCCGAGGTCTTTCTCCATTGCCACCGAGCTGTTCGAAGGCAACTTCGCACCGGGGTGCAGCCCGTTCAGCCTGTTCCTCATGTGGAGTCCTCGCATCGAAGCAGTGACCCACAACTATTTGAGTCGCCCACCACGTGCTCTGCCAATTTGCAGAACGATGGTGAGGGACGCGCTATCGGAGGTGGCATCCCAACAGCAATACCTGAAGGGAGCGATGTCGAACAGGTATGCCATGCCTCTCACTACGGGTGATGGCCAGCATAGAGCCGTGAAGGGGGCTCCCAGTGCCCTTCCACCAACGGGGGTGTGTACCCAGGCTTCTAAGTGAGGCTTCGCTTCCCGCCGGAAGTCCACGGCGGTTCTGTTCCTCCCAAGGAGTACGGCAACAACCCACCTTGGGAAAGTGGGGACCCCAGCACTAACTCCTTTAACTAGGCGGGCGTGCTGGTTACAGTAGGAGGGGGCAGTGTGCATCAAAAACTGAGCCCCACCACAACTCTCATCCACGGGGTGGTTGGGACGCAGGTGTTAGAGGGATCGCCAGCCCTCAGGATAGTGAGTTCCCGCATAGGGATAAGCTGTCCCCCTGCGACGTAGCGGTAGAACACGTGGGATTGGGGATGACCTTGTCGACCGTTCGTCGGTCCCCTGCTCTGTCGAGCTGGCAAGGCGCCCACAGGTTCTGCGCTGCTACTGAAGTTGGTGGTGGATGTCTCGCCCAAAAAGACCATAAACGCGCGGGATAAGGCCCTCTCCACCTTCGCCGGGTTAGGCTAGAGTCAGAGCTGCATGACTATAACTAGCGGCCGATCCAGTTGCACGACTGGTGGTCCCCCTCAGTGTCTCGGTTGTCTGCCGAGTGGGCGGTGGTCGGATTCCACCACACCCTGCCACGAGGTGCGTGGAGACTTGGCCAGTCTAGGCTCGTCGTAATTAGTTGCAGCGACGTTAAACAACCCGTCCGGGCATATAATAGGACCGGTTATGCTTCTTCTTCTCCTTCTTAGCCAGGTGGTTACCTCCCTGGCGCCC';
