import { motifSearch } from './motifSearch';

test('`function motifSearch()`', () => {
  // string inputs
  var matches = motifSearch('CUGCCA', PEMV2);

  expect([...matches].map(m => m.index)).toStrictEqual([1896, 2001, 3357, 4105]);
  expect([...matches].map(m => m.position)).toStrictEqual([1897, 2002, 3358, 4106]);

  [...matches].forEach(m => expect(m.length).toBe(6));

  // nucleobase inputs
  var matches = motifSearch(
    [...'CUGCCA'].map(c => new NucleobaseMock(c)),
    [...PEMV2].map(c => new NucleobaseMock(c)),
  );

  expect([...matches].map(m => m.index)).toStrictEqual([1896, 2001, 3357, 4105]);
  expect([...matches].map(m => m.position)).toStrictEqual([1897, 2002, 3358, 4106]);

  [...matches].forEach(m => expect(m.length).toBe(6));

  // nucleobase sequence
  var matches = motifSearch(
    'CUGCCA',
    [...PEMV2].map(c => new NucleobaseMock(c)),
  );

  expect([...matches].map(m => m.index)).toStrictEqual([1896, 2001, 3357, 4105]);
  expect([...matches].map(m => m.position)).toStrictEqual([1897, 2002, 3358, 4106]);

  [...matches].forEach(m => expect(m.length).toBe(6));

  // nucleobase motif
  var matches = motifSearch(
    [...'CUGCCA'].map(c => new NucleobaseMock(c)),
    PEMV2,
  );

  expect([...matches].map(m => m.index)).toStrictEqual([1896, 2001, 3357, 4105]);
  expect([...matches].map(m => m.position)).toStrictEqual([1897, 2002, 3358, 4106]);

  [...matches].forEach(m => expect(m.length).toBe(6));

  // custom options
  var matches = motifSearch('CUGCCA', PEMV2, {
    cutoff: 0.9,
    mismatchPenalty: -2,
    gapPenalty: -2,
  });

  expect([...matches].map(m => m.position)).toStrictEqual([1897, 2002, 3358, 4106]);

  // IUPAC codes
  var matches = motifSearch('CYGCCNR', PEMV2, {
    cutoff: 0.9,
    mismatchPenalty: -2,
    gapPenalty: -2,
  });

  expect([...matches].map(m => m.position)).toStrictEqual([625, 1018, 2002, 2744, 3358, 3558, 4071]);

  var seq = [...PEMV2].map(c => new NucleobaseMock(c));

  // bases with empty text content
  seq[50] = new NucleobaseMock('');
  seq[100] = new NucleobaseMock('');

  var matches = motifSearch('CUGCCA', seq);

  expect([...matches].map(m => m.position)).toStrictEqual([1897, 2002, 3358, 4106]);

  var motif = [...'CUGCCA'].map(c => new NucleobaseMock(c));

  // bases with text content containing more than one character
  motif[2] = new NucleobaseMock('AG');
  motif[4] = new NucleobaseMock('asdf');

  var matches = motifSearch(motif, PEMV2);

  expect([...matches].length).toBe(0);

  // empty motif
  expect([...motifSearch('', PEMV2)].length).toBe(0);

  // empty sequence
  expect([...motifSearch('CUGCCA', '')].length).toBe(0);
});

class NucleobaseMock {
  #textContent;

  constructor(textContent) {
    this.#textContent = textContent;
  }

  get textContent() {
    return this.#textContent;
  }
}

const PEMV2 = 'GGGTATTTATAGAGATCGGTATGAACTGTGTTGCTAGAATTAAGCGGTGGTTCACACCTGACTTCACCCCTGGCGAGGGTGTTAAGTCCAGAGCTCAGCTGGAAAGGGAGTTGGATCCTACTTGGGCGCTTCTCGTGTGTCAAGAGCGAGCGCGCCGCGATGCTGACAGTATCACCAATGAGTGGTACGAGGGCAGCATGGAGTGTAACCTCCTTATCCCTCGGCCCAAGGCTGAGGATGTTTTAGGCCCCTCCGTCGCCCCTGAGCCCGTGGCTCTAGTGGAGGAGATTACCCGTCCCCACGCGCCGTGCGTGGATGCCCCTGCCGTGGAGTCCAGCGAGCTGGCGGAGATTGATCCCGCTGACCTTGCCAAGTTCGACTCCCTCAATCGTCGCCTGTTGGCTGAAGCCAACTCATGCAGGGAGATAGTTCTGTGGGTGCCTCCTGGCCTACCAGCAGAGCGTGACGTGTTGCCCAGGGCACGTGGGGTGATAATGATCCCCGAAGTCCCTGCCTCCTCATACACCTTGTCCGTGAAGGTGATGGAGGCTGTGCGGTTGGCACAGGAAGTCTTGGCGTCCCTTGCCAAGAGGGCCTCAGAGAAGATGGCCCCACCAGCCCCTACCGCCCAGGCCCAGCCAGAGGCTACCCTGTCGGGATGCGACTACCCGTATCAGGAAACTGGAGCAGCAGCTGCGTGGGTGACGCCTGGCTGCATTGCCATGGAGCTTAGAGCCAAATTTGGCATCTGTAGACGGACCCCCGCTAACTTAGAGATGGGGAGTCGTGTTGCCCGCGAGCTCCTGCGGGATAACTGTGTCACCTGCAGGGAGACCACGTGGTACACGAGTGCCATTGCTGTGGACCTGTGGTTGACCCCAACGGTCGTCGACCTAGCCTGTGGTCGGCGGGCGGTGGATTTTTGGTAGGGGCTGTGCTGCCTCGGCTGGGGGAAGACACTAGTGTAAGGTTTGACAACCTGCACCCCAGCATCGAGGTAATCAAGGCGGCTAGGCCCCGCCCAACCCAGAGGATGTCGTACCAAATCGACGTTGTGCGTCCTCTCGGTGATTTTGGTGTGCACAACAACTCCCTTGTCAACCTAGCCAGGGGAATCAATGAAAGGGTGTTCTACACGGACAATGCTAGGACAGAACCCCTCAAGCCTAAGGTTCCCTTTCCCTCGTCACGGGAACTGAAAACCTTCAGAGTCACCCCTTGGACCATGGATAGGGTTGTGGAAAGTTACACTGGGTCTCAGCGCATTCGTTATGCTAGCGCACGGGACAGCATTTTATCCAACCCACTGAGTTCTAAGGATGCCCGGGTCAAGACGTTTGTGAAAGCTGAAAAGATAAATTTTACAGCCAAACCTGACCCCGCCCCTCGTGTGATACAGCCTAGGGATCCACGATTCAACATTGTCCTGGCTAAGTATATCAAGCCATTGGAACCGATGTTGTACAAAGCTCTCGGGAGACTTTACAAGTACCCCGCAGTCGCTAAGGGGTTTAACGCGGTTGAGACGGGAGAAATCATCGCTGGGAAATGGCGGTGTTTTAAAGATCCCGTTGTCGTGGGATTAGACGCTTCCCGATTTGATCAGCATGTATCTGTTGAGGCGTTGCAATTTACCCACGCAGTGTACAGGGGGTTCATCAAGTCCCGGGAGTTCAACAACCTCCTGCAGATGATGTACACCAACCGTGGGCTAGGGTCTGCTAAGGACGGGTTTGTCCGTTACAAGGTTAAGGGCAGACGCATGAGCGGAGATATGGACACCTCCTTGGGAAACTGCGTTCTCATGGTGTTACTCACCAGGAATCTTTGCAAGATTCTAGGCATCCCGCACGAGCTCTTCAACAATGGTGACGATTGTATCGTCTTTTTTGATCGCTGCCATTTGGAAAAGTTCAACAATGCTGTCAAGCCCTATTTTGCAGACCTCGGGTTTAAGATGAAGGTGGAGCCACCGGTAGACGTGCTCGAGAAAGTTGAGTTCTGCCAAACACAGCCTATATATGACGGGGAGAAGTGGCGCACCGTGCGCAGCATCTCGAGCATTGGGAAAGACTGCTCATCCGTCATTGGTTGGGACCAATTAGAGGGGTGGTGGGATGCCATCGCCCAGAGTGGTCTGGCTGTGTGTGGTGGGATGCCCATATACACGTCGTTTTACCGGTGGTTGGCACGGGCTGGTAAAAGTGGGACTAAGTGCCAGTCACACCCTTTATGGAAGAACGAGGGGTTGAATTGGTACAGGATGGGGATGGACCTTTCTCATGAAGTCAATGTCACCCCTCAGGCGCGTCTGTCTTTTTTCGCGGGGTTTGGAATTTCCCCCCCCATGCAGGTTGCTATTGAGGCGTTGTATGACAGGCTACCTCCACCGTCCCCCCACTACGGCTCTCCGGTTACGGTTGTAACACAGCGAGTGTTCACCAATTATTTCACGCCGGAAGCTACCTGTGTCAGCATGAGCACCAATGGAGACAACAAATCTGACTTTGCTGTGTACGGTCCTGCGCCGACAGTGATGTCTCTCTGCGCTCAGTGTTAGGCTTGTAATAGCGATGGCGTGGCTCGACCACACCCTGGATAGACAGGGTTTAGATCAAGGGAAGCCGGGGAGTCACCAACCCCACCCTGAATCGACAGGGCAAAAAGGGAAGCCGGGCATCGCCCACGTGGAATTGACCACGTCACCTTTTCGCGTCGACTGTATTGTCAACACCCCTTCGGTCCGCCAGCCTAGGACAATGGCGGTTGGGTGATATATGACGATAATCATTAATGTCAACAACGACGAGCGCAAGCAACCAGAAGGAGCTACTGGCAGCTCTGTACGGCGAGGTGACAATAAAGGAACTCGAGGAAACAAACCTCGGAGTCATCACCCCGGTTCGCGCGAACGAAAAGGTTACACTCACCCCTCTCCTACCCCCAAAAACTCAAGGCAGGGTCAGCTCCGTCCTGAAGCGGTTCAGGAGCACCCGAAACACGGGGGGACTACTTTCCGTGGAGAAAGTAGTGGTAGTGTTCACCCCTCACGTCCCAGACGACGTGCTAGGAGAGGTGGAGATATGGCTCCACGACAGCATCCTCCCCCACCTCGGGAGCGTCGGACCAAGGTTGAGACTCAAGCTGAGCGACGGGCCCAAGCTCTTAGCGTTTTACCCACCCTACTCGATTGCATTGGGGGACTCAATCTCGGGCCAGCCGAGGTCTTTCTCCATTGCCACCGAGCTGTTCGAAGGCAACTTCGCACCGGGGTGCAGCCCGTTCAGCCTGTTCCTCATGTGGAGTCCTCGCATCGAAGCAGTGACCCACAACTATTTGAGTCGCCCACCACGTGCTCTGCCAATTTGCAGAACGATGGTGAGGGACGCGCTATCGGAGGTGGCATCCCAACAGCAATACCTGAAGGGAGCGATGTCGAACAGGTATGCCATGCCTCTCACTACGGGTGATGGCCAGCATAGAGCCGTGAAGGGGGCTCCCAGTGCCCTTCCACCAACGGGGGTGTGTACCCAGGCTTCTAAGTGAGGCTTCGCTTCCCGCCGGAAGTCCACGGCGGTTCTGTTCCTCCCAAGGAGTACGGCAACAACCCACCTTGGGAAAGTGGGGACCCCAGCACTAACTCCTTTAACTAGGCGGGCGTGCTGGTTACAGTAGGAGGGGGCAGTGTGCATCAAAAACTGAGCCCCACCACAACTCTCATCCACGGGGTGGTTGGGACGCAGGTGTTAGAGGGATCGCCAGCCCTCAGGATAGTGAGTTCCCGCATAGGGATAAGCTGTCCCCCTGCGACGTAGCGGTAGAACACGTGGGATTGGGGATGACCTTGTCGACCGTTCGTCGGTCCCCTGCTCTGTCGAGCTGGCAAGGCGCCCACAGGTTCTGCGCTGCTACTGAAGTTGGTGGTGGATGTCTCGCCCAAAAAGACCATAAACGCGCGGGATAAGGCCCTCTCCACCTTCGCCGGGTTAGGCTAGAGTCAGAGCTGCATGACTATAACTAGCGGCCGATCCAGTTGCACGACTGGTGGTCCCCCTCAGTGTCTCGGTTGTCTGCCGAGTGGGCGGTGGTCGGATTCCACCACACCCTGCCACGAGGTGCGTGGAGACTTGGCCAGTCTAGGCTCGTCGTAATTAGTTGCAGCGACGTTAAACAACCCGTCCGGGCATATAATAGGACCGGTTATGCTTCTTCTTCTCCTTCTTAGCCAGGTGGTTACCTCCCTGGCGCCC';
